### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Doanduy09** [NONGFAH/luci-app-athena-led#2]
I have a text on github, now I want to display the running text on the jdc, I have added the link but it does not run.
Path https://raw.githubusercontent.com/phuongkhpt/thoitiet/refs/heads/main/homnay
![Screenshot (618)](https://github.com/user-attachments/assets/71421a1f-8b81-442e-82f7-106e9112963f)

**Comment by NONGFAH** [comment]
https://github.com/NONGFAH/luci-app-athena-led/releases/tag/0.0.7

**Comment by Doanduy09** [comment]
I need to pass the date variable to the url, but the url does not work.thanks you

**Comment by Doanduy09** [comment]
https://raw.githubusercontent.com/phuongkhpt/thoitiet/main/thoitiet.txt?token=$(date +%s) not working, pls fix help me $date
