### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by Doanduy09** [NONGFAH/luci-app-athena-led#3]
https://raw.githubusercontent.com/phuongkhpt/thoitiet/main/thoitiet.txt?token=$(date +%s) not working, pls fix help me $date

**Comment by NONGFAH** [comment]
You can develop your own HTTP service and deploy it to an accessible server. This way, you can customize any content. This project is not responsible for the HTTP service part.

**Comment by NONGFAH** [comment]
你可以对这个项目进行赞助。我会帮你实现一个独立的http程序来实现你的功能

**Comment by phuongkhpt** [comment]
Hello @NONGFAH , this is project use get api openweathermap and cut value , return text on to file thoitiet.txt
file on githubusercontent have x-cache not show new context . function token= $date have get new context update
curl  https://raw.githubusercontent.com/phuongkhpt/thoitiet/main/thoitiet.txt?token=$(date +%s) new context update on time

**Comment by NONGFAH** [comment]
cool

**Comment by phuongkhpt** [comment]
@NONGFAH i have edit athena-led on file luci-app-athena-led/root/etc/init.d/athena_led but slow get new 5min , you have faster to 1min ?
https://anotepad.com/notes/k9yjynb5

**Comment by NONGFAH** [comment]
I think you should implement a backend service that encapsulates variables into your program.
